use crate::plan_io::{atomic_write, combine, inline_evidence, md_escape, quote};
use crate::runner;
use anyhow::{anyhow, Result};
use fs2::FileExt;
use kei_arch_map::schema::{self, Evidence, Plan};
use std::fmt::Write as _;
use std::fs::{File, OpenOptions};
use std::path::Path;
use toml_edit::DocumentMut;

pub fn run(plan_path: &Path, out_path: &Path) -> Result<()> {
    let root = runner::repo_root(plan_path)?;
    runner::confine_out(out_path, &root)?;
    let plan = schema::load(plan_path)?;
    let body = render_audit(&plan, &root);
    std::fs::write(out_path, body)?;
    println!("wrote {}", out_path.display());
    Ok(())
}

fn render_audit(plan: &Plan, root: &Path) -> String {
    let mut out = String::new();
    out.push_str("# Claims Audit\n\n");
    out.push_str("> Generated by `kei-arch-map plan`. Real-time evidence verification.\n\n");
    out.push_str("| Module | Claim | Status | Evidence |\n");
    out.push_str("|---|---|---|---|\n");
    let (total, pass, fail) = render_rows(&mut out, plan, root);
    let _ = writeln!(out, "\nTotal: {} | PASS: {} | FAIL: {}", total, pass, fail);
    out
}

fn render_rows(out: &mut String, plan: &Plan, root: &Path) -> (usize, usize, usize) {
    let mut total = 0usize;
    let mut pass = 0usize;
    let mut fail = 0usize;
    for module in &plan.modules {
        for claim in &module.claims {
            total += 1;
            let (ok, _r) = runner::check_claim(claim, root);
            let status = if ok { "PASS" } else { "FAIL" };
            if ok {
                pass += 1;
            } else {
                fail += 1;
            }
            let repr = schema::evidence_repr(&claim.evidence);
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | `{}` |",
                module.id, claim.id, status, md_escape(&repr)
            );
        }
    }
    (total, pass, fail)
}

/// Append a claim to PLAN.toml. Holds an exclusive advisory file lock on a
/// dedicated `<plan>.lock` companion file for the entire read→parse→write
/// →rename transaction (security fix F: lock-across-transaction). Two
/// concurrent `add_claim` calls cannot both pass `ensure_unique` and both
/// write — the second blocks on lock acquisition until the first's atomic
/// rename has landed.
pub fn add_claim(
    plan_path: &Path,
    module_id: &str,
    claim_id: &str,
    description: &str,
    evidence_json: &str,
) -> Result<()> {
    let evidence: Evidence = serde_json::from_str(evidence_json)
        .map_err(|e| anyhow!("parse evidence_json: {}", e))?;
    let lock = acquire_lock(plan_path)?;
    let original = std::fs::read_to_string(plan_path)
        .map_err(|e| anyhow!("read {}: {}", plan_path.display(), e))?;
    let doc: DocumentMut = original
        .parse()
        .map_err(|e| anyhow!("parse {}: {}", plan_path.display(), e))?;
    ensure_unique(&doc, module_id, claim_id)?;
    let block = render_claim_block(claim_id, description, &evidence)?;
    let combined = combine(&original, &block);
    let _verify: DocumentMut = combined
        .parse()
        .map_err(|e| anyhow!("re-parse after append: {}", e))?;
    atomic_write(plan_path, &combined)?;
    drop(lock);
    println!(
        "appended {}::{} to {}",
        module_id, claim_id, plan_path.display()
    );
    Ok(())
}

/// Open companion `<plan>.lock` and acquire exclusive advisory lock.
/// Lock is released when the returned File handle is dropped.
fn acquire_lock(plan_path: &Path) -> Result<File> {
    let mut lock_path = plan_path.to_path_buf();
    let mut new_name = lock_path
        .file_name()
        .ok_or_else(|| anyhow!("plan path has no file name"))?
        .to_os_string();
    new_name.push(".lock");
    lock_path.set_file_name(new_name);
    let f = OpenOptions::new()
        .create(true)
        .read(true)
        .write(true)
        .truncate(false)
        .open(&lock_path)
        .map_err(|e| anyhow!("open lock {}: {}", lock_path.display(), e))?;
    FileExt::lock_exclusive(&f)
        .map_err(|e| anyhow!("lock {}: {}", lock_path.display(), e))?;
    Ok(f)
}

/// Verify (module_id, claim_id) is not already declared.
fn ensure_unique(doc: &DocumentMut, module_id: &str, claim_id: &str) -> Result<()> {
    let modules = doc
        .get("module")
        .and_then(|i| i.as_array_of_tables())
        .ok_or_else(|| anyhow!("plan has no [[module]] entries"))?;
    let mut module_seen = false;
    for m in modules.iter() {
        let id = m.get("id").and_then(|v| v.as_str()).unwrap_or("");
        if id != module_id {
            continue;
        }
        module_seen = true;
        if let Some(claims) = m.get("claim").and_then(|i| i.as_array_of_tables()) {
            for c in claims.iter() {
                let cid = c.get("id").and_then(|v| v.as_str()).unwrap_or("");
                if cid == claim_id {
                    return Err(anyhow!(
                        "claim `{}` already exists in module `{}`",
                        claim_id, module_id
                    ));
                }
            }
        }
    }
    if !module_seen {
        return Err(anyhow!("module `{}` not found in plan", module_id));
    }
    Ok(())
}

/// Render a `[[module.claim]]` block as TOML text.
fn render_claim_block(
    claim_id: &str,
    description: &str,
    evidence: &Evidence,
) -> Result<String> {
    let evidence_toml = toml::to_string(evidence)
        .map_err(|e| anyhow!("serialize evidence: {}", e))?;
    let mut block = String::new();
    let _ = writeln!(block, "\n[[module.claim]]");
    let _ = writeln!(block, "id = {}", quote(claim_id));
    let _ = writeln!(block, "description = {}", quote(description));
    let _ = writeln!(block, "{}", inline_evidence(&evidence_toml));
    Ok(block)
}
