use crate::schema::{self, Claim, Evidence, Plan};
use crate::verify;
use anyhow::{anyhow, Result};
use std::fmt::Write as _;
use std::path::Path;

pub fn run(plan_path: &Path, out_path: &Path) -> Result<()> {
    let plan = schema::load(plan_path)?;
    let root = verify::repo_root(plan_path);
    let body = render_audit(&plan, &root);
    if let Some(parent) = out_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(out_path, body)?;
    println!("wrote {}", out_path.display());
    Ok(())
}

fn render_audit(plan: &Plan, root: &Path) -> String {
    let mut out = String::new();
    out.push_str("# Claims Audit\n\n");
    out.push_str("> Generated by `kei-arch-map plan`. Real-time evidence verification.\n\n");
    out.push_str("| Module | Claim | Status | Evidence |\n");
    out.push_str("|---|---|---|---|\n");
    let (total, pass, fail) = render_rows(&mut out, plan, root);
    let _ = writeln!(out, "\nTotal: {} | PASS: {} | FAIL: {}", total, pass, fail);
    out
}

fn render_rows(out: &mut String, plan: &Plan, root: &Path) -> (usize, usize, usize) {
    let mut total = 0usize;
    let mut pass = 0usize;
    let mut fail = 0usize;
    for module in &plan.modules {
        for claim in &module.claims {
            total += 1;
            let (ok, _reason) = verify::check_claim(claim, root);
            let status = if ok { "PASS" } else { "FAIL" };
            if ok {
                pass += 1;
            } else {
                fail += 1;
            }
            let repr = schema::evidence_repr(&claim.evidence);
            let _ = writeln!(
                out,
                "| `{}` | `{}` | {} | `{}` |",
                module.id,
                claim.id,
                status,
                md_escape(&repr)
            );
        }
    }
    (total, pass, fail)
}

pub fn add_claim(
    plan_path: &Path,
    module_id: &str,
    claim_id: &str,
    description: &str,
    evidence_json: &str,
) -> Result<()> {
    let mut plan = schema::load(plan_path)?;
    let evidence: Evidence = serde_json::from_str(evidence_json)
        .map_err(|e| anyhow!("parse evidence_json: {}", e))?;
    let module = plan
        .modules
        .iter_mut()
        .find(|m| m.id == module_id)
        .ok_or_else(|| anyhow!("module `{}` not found in plan", module_id))?;
    if module.claims.iter().any(|c| c.id == claim_id) {
        return Err(anyhow!(
            "claim `{}` already exists in module `{}`",
            claim_id,
            module_id
        ));
    }
    module.claims.push(Claim {
        id: claim_id.to_string(),
        description: description.to_string(),
        evidence,
    });
    let serialized = toml::to_string_pretty(&plan)?;
    std::fs::write(plan_path, serialized)?;
    println!("appended {}::{} to {}", module_id, claim_id, plan_path.display());
    Ok(())
}

fn md_escape(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}
